name: Run Cosmonova Bot

on:
  schedule:
    - cron: '*/3 * * * *'  # Runs every 3 minutes
  workflow_dispatch:       # Manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'   # Puppeteer requires Node.js 18 or higher

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer Chrome browser
        run: npx puppeteer browsers install chrome

      - name: Run the bot script
        run: node index.js