name: Run Cosmonova Bot

on:
  schedule:
    - cron: '30 0 * * *'   # Runs every day at 00:30
    - cron: '45 9 * * *'    # Runs every day at 09:45
    - cron: '15 12 * * *'   # Runs every day at 12:15
    - cron: '15 17 * * *'   # Runs every day at 17:15
  workflow_dispatch:          # Allows you to manually trigger the workflow

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Run the bot script
        run: node index.js

        - name: Install Puppeteer browsers
        run: npx puppeteer install