name: Run Cosmonova Bot

on:
  schedule:
    - cron: '15 12,17 * * *'  # Runs every day at 12:15 PM and 5:15 PM
  workflow_dispatch:          # Allows you to manually trigger the workflow

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run the bot script
        run: node index.js