name: Run Cosmonova Bot

on:
  schedule:
        - cron: '0 8,10,12,14,16,18,20,22,0 * * *'  # Runs at 08:00, 10:00, 12:00, etc.
  workflow_dispatch:       # Allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run the bot script
        run: node index.mjs