name: Run Cosmonova Bot

on:
  push:
    branches:
      - github  # Trigger on the 'github' branch
  schedule:
    - cron: '0 8,10,12,14,16,18,20,22,0 * * *'  # Runs at specific times
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'   # Puppeteer requires Node.js 18 or higher

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer Chrome browser
        run: npx puppeteer browsers install chrome  # Ensure compatible Chrome is installed

      - name: Run the bot script
        run: node index.mjs
